### ISSUE TITLE
proFIA fails to byte-compile and prepare package for lazy loading

### ISSUE THREAD

**Issue by sneumann** [adelabriere/proFIA#1]
Hi, in https://cloud.docker.com/u/bioconductor/repository/registry-1.docker.io/bioconductor/devel_mscore2/builds/d7a4ddb7-52ab-494a-b572-e88142c3d283
```
* installing *source* package ‘proFIA’ ...
** using staged installation
** libs
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c FIABandsExtractionCentroid.c -o FIABandsExtractionCentroid.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c UtilFunc.c -o UtilFunc.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fastMatchPpm.c -o fastMatchPpm.o
gcc -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o proFIA.so FIABandsExtractionCentroid.o UtilFunc.o fastMatchPpm.o -L/usr/local/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-proFIA/00new/proFIA/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  : 
  The prototype for class “proFIAset” has undefined slot(s): 'fClasses'
Error: unable to load R code in package ‘proFIA’
Execution halted
ERROR: lazy loading failed for package ‘proFIA’
* removing ‘/usr/local/lib/R/site-library/proFIA’
```
There is no failure on http://bioconductor.org/checkResults/3.8/bioc-LATEST/proFIA/

There is some mismatch between `classes` and fClasses` in https://github.com/adelabriere/proFIA/blob/master/R/classContainer.R#L84

Yours, Steffen

**Comment by adelabriere** [comment]
Hi thanks for telling me,

I was busy relocating for my postdoc. I m trying to dix the issue right now. Sorry for the delay.

Regards ,
Alexis

Le 6 avr. 2019 1:17 PM, Steffen Neumann <notifications@github.com> a écrit :

Hi, in https://cloud.docker.com/u/bioconductor/repository/registry-1.docker.io/bioconductor/devel_mscore2/builds/d7a4ddb7-52ab-494a-b572-e88142c3d283

* installing *source* package ‘proFIA’ ...

** using staged installation

** libs

gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c FIABandsExtractionCentroid.c -o FIABandsExtractionCentroid.o

gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c UtilFunc.c -o UtilFunc.o

gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fastMatchPpm.c -o fastMatchPpm.o

gcc -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o proFIA.so FIABandsExtractionCentroid.o UtilFunc.o fastMatchPpm.o -L/usr/local/lib/R/lib -lR

installing to /usr/local/lib/R/site-library/00LOCK-proFIA/00new/proFIA/libs

** R

** inst

** byte-compile and prepare package for lazy loading

Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  :

  The prototype for class “proFIAset” has undefined slot(s): 'fClasses'

Error: unable to load R code in package ‘proFIA’

Execution halted

ERROR: lazy loading failed for package ‘proFIA’

* removing ‘/usr/local/lib/R/site-library/proFIA’



There is no failure on http://bioconductor.org/checkResults/3.8/bioc-LATEST/proFIA/

There is some mismatch between classes and fClasses` in https://github.com/adelabriere/proFIA/blob/master/R/classContainer.R#L84

Yours, Steffen

**Comment by sneumann** [comment]
Accepting the PR should fix this. Yours, Steffen

**Comment by sneumann** [comment]
One more thing:

great, proFIA is now building at
http://bioconductor.org/checkResults/devel/bioc-LATEST/proFIA/

But you also need to bump the version number to 1.9.2, 
because the new tarballs only migrate to the download area 
in case of a new version number. Don't forget pushing to BioC ;-)

Yours,
Steffen

**Comment by sneumann** [comment]
Great, confirmed to work. Yours, Steffen
